on:
  push:
    branches: [ main ]
    pull_request:
    merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: DeterminateSystems/magic-nix-cache-action@v3
      with:
        diagnostic-endpoint: "" 
    - run: nix flake check
